name: unizer
description: Unizer Mobile
version: 4.0.0+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_spinkit: ^5.0.0
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.2.2
  animated_text_kit: ^4.2.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  date_format: ^2.0.2
  shared_preferences: ^2.0.6
  easy_localization: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  flutter_html: ^2.1.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


module:
  androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/i18n/en-US.json
    - assets/i18n/nl-NL.json

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf

    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf